# Generated by Django 2.2.7 on 2020-01-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
